version: 2

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    steps:
      - run: apk add git openssh-client
      - checkout
      - run: ./cake.sh -target=test

workflows:
  version: 2
  test:
    jobs:
      - test
